site_name: Traum SOPs
site_url: https://wiki.traumwood.team
theme:
  name: material
  palette:
    primary: black
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Engineering:
    - Drafting Workflow:
      - Work Orders: Innergy/work-orders.md
      - File Standards: Engineering/file-standards.md
      - Internal Review: Engineering/internal-review.md
      - Finish Callouts: Engineering/finish-shopdrawings.md
      - Submittals: Engineering/submittals.md
      - Drafting Kanban: Engineering/drafting-kanban.md
      - Release to Stockbilling: Engineering/release-to-stockbilling.md
  - Production:
    - Handoff Agenda: Production/handoff-agenda.md
    - Install Kits: Production/install-kits.md
    - Shop Fit-Up: Production/trim-out-elevation.md
    - Balance Standards: Production/balance-standards.md
    - Samples Process: Production/samples-process.md
    - Shop Supplied Tools: Production/shop-supplied-tools.md
    - Fabrication Standards:
      - Hardware Standards: Production/hardware-standards.md
      - Hinge Placement: Production/hinge-placement.md
      - Die Walls: Production/die-walls.md
      - Rollout Standards: Production/rollout-standards.md
      - Solid Wood Edges: Production/solid-wood-edges.md
      - Painted Cabinets / Edgebanding: Production/painted-cabinets-edgebanding.md
      - Finished Bottom Panel: Production/finished-bottom-panel.md
      - Shippable Item Size: Production/shippable-item-size.md
      - Sink Aprons: Production/sink-aprons.md
      - Sheppard Brackets: Production/sheppard-brackets.md
      - Shelf Setback: Production/shelf-setback.md
    - Fire Doors:
      - 20 Min Jamb: Production/fire-doors/20-min-jamb.md
      - 20 Min Slab: Production/fire-doors/20-min-slab.md
      - 20 Min Stile & Rail: Production/fire-doors/20-min-stile_rail.md
      - 60 Min Jamb: Production/fire-doors/60-min-jamb.md
      - 60 Min Slab: Production/fire-doors/60-min-slab.md
      - 60 Min Stile & Rail: Production/fire-doors/60-min-stile_rail.md
  - Purchasing:
    - Overview: purchasing-process.md
    - Stock Materials: purchasing-stock.md
    - Non-Stock Materials: purchasing-non-stock.md
    - Receiving: receiving-process.md
  - Innergy:
    - Project Information: Innergy/project-information.md
    - Material Cards: Innergy/material-cards.md
    - Work Orders: Innergy/work-orders.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
